Gamma
NFCSKL/NFC-ViAn pull request #164
Opened 2018-10-16 08:58 UTC by henpe071

Added the option of changing the gamma value in the manipulator widget. The gamma functions the same way as contrast and brightness does.

2018-10-16 09:00 UTC, henpe071 commented on ViAn/GUI/videowidget.cpp
> -int VideoWidget::get_brightness() {
These were unused

2018-10-16 19:06 UTC, niklasniklas requested changes
No gamma in report. (reportgenerator.cpp line 61)

2018-10-16 19:06 UTC, niklasniklas commented
Otherwise fine! :-)

2018-10-21 19:59 UTC, niklasniklas approved these changes
Works fine

2018-10-23 07:57 UTC, merged