Temp save
NFCSKL/NFC-ViAn pull request #8
Opened 2018-02-13 13:40 UTC by henpe071

When creating a new project, everything is created in a temp folder. Clicking save will move the project to the assign folder.  Open project will also "open" the project in a temp folder. all changes made to the project are only saved in this temp folder and only recorded in the correct folder upon clicking save. 

When clicking save, a pop-up will appear if a project already exist in the assigned folder asking if you're sure you wanna overwrite the existing project. 

I might also have done some small cleanups in the code concerning some brackets and variable names.

2018-02-18 12:52 UTC, fredrikiselius requested changes
The new additions broke both the new project window and recent project window for me. See code specific comments

2018-02-18 12:52 UTC, fredrikiselius commented on ViAn/GUI/projectwidget.cpp
> +        QMessageBox msg_box;
We've added quite alot of message boxes. We should refactor this type of code snippet into a function,

2018-02-18 12:52 UTC, fredrikiselius commented on ViAn/Project/project.cpp
> +    if(proj->tmp_dir.isValid()){
And if its not? isValid() returns false if the temporary dir could not be created. This needs to be handled somehow. Wont it try to save to a nonexistent directory if it fails?

2018-02-18 12:52 UTC, fredrikiselius commented on ViAn/Project/project.cpp
> +    if(tmp_dir.isValid()){
Same with this isValid()

2018-02-18 12:52 UTC, fredrikiselius commented on ViAn/GUI/projectwidget.cpp
> +    delete proj_dialog;
The new project dialog is closed directly after it opens due to the delete here.

2018-02-18 12:52 UTC, fredrikiselius commented on ViAn/GUI/projectwidget.cpp
> +    QDir dir(QString::fromStdString(m_proj->get_dir()));
This popup is triggered on each save. It should only happen when the project has never been saved to that location before.

2018-02-18 12:52 UTC, fredrikiselius commented on ViAn/GUI/projectwidget.cpp
> +    rp.update_recent(m_proj->get_name(), m_proj->get_file());
This no longer updates the recent projects list

2018-02-22 14:59 UTC, henpe071 commented
Now the things should be fixed and I also fix a small thing I missed before.

2018-03-01 08:09 UTC, fredrikiselius commented on ViAn/GUI/projectwidget.cpp
> +        delete m_proj;
Won't this put the program in a state without a project?

2018-03-01 08:09 UTC, fredrikiselius commented on ViAn/Project/recentproject.cpp
> +    if (recent_items.size() >= 10) recent_items.resize(10);
10 should be made a constant

2018-03-01 08:41 UTC, fredrikiselius approved these changes

2018-03-01 08:42 UTC, merged